# Generated by Django 4.0.4 on 2022-04-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата')),
                ('name', models.TextField(max_length=100, verbose_name='Название')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('interval', models.FloatField(verbose_name='Расстояние')),
            ],
            options={
                'verbose_name': 'Таблица',
                'verbose_name_plural': 'Таблицы',
                'db_table': 'table_db',
            },
        ),
    ]
